### ISSUE TITLE
Can't publish the config file 

### ISSUE THREAD

**Issue by WhalesHaveAccents** [tanthammar/tall-blueprint-addon#1]
@tanthammar 

After installing, you get the following error  `Unable to locate publishable resources.` when running:
```console
php artisan vendor:publish --tag=tall-blueprint-config
```
After looking at: 
>vendor>tanthammer>tall-blueprint-addon>src>TallBlueprintAddonServiceProvider.php line 27
```php
'tall_forms_blueprint'
```
I changed it to:
```php
tall-blueprint-config
```
and it exported the file 👍 

Think it needs updating.....

**Comment by tanthammar** [comment]
@WhalesHaveAccents 
Thank you for telling me. I forgot to change the Readme.
It is updated now.

**Comment by WhalesHaveAccents** [comment]
no worries, also it doesn't work with the latest Tall Forms? it required you to downgrade to ^7.8.4
