### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by robsox** [tanthammar/tall-blueprint-addon#4]
Hello,

There appears to be a config issue somewhere (or I'm doing something stupid).

Running composer require --dev tanthammar/tall-blueprint-addon actually installs the Naoray\BlueprintNovaAddon in the tanthammar vendor folder rather than the Tall Forms addon.

**Comment by jichiduo** [comment]
Hello,

I freshly install the laravel and blueprint and tall-forms, when I try to install this add-on  got the different error 

``` bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires tanthammar/tall-blueprint-addon ^1.5 -> satisfiable by tanthammar/tall-blueprint-addon[v1.5.0].
    - tanthammar/tall-blueprint-addon v1.5.0 requires laravel-shift/blueprint ^1.18 -> found laravel-shift/blueprint[v1.18.0, ..., v1.25.0] but it conflicts with your root composer.json require (^2.1).
```

**Comment by tanthammar** [comment]
Thank you for reporting. Please try with version 2.0 (or dev-master).
I had the same issue myself. Missed that Blueprint released a new version.
