### ISSUE TITLE
Please put : array in the class.stub.php

### ISSUE THREAD

**Issue by rabol** [tanthammar/tall-blueprint-addon#6]
Please change:

```
 protected function fields()
    {
        return [
            // fields...
        ];
    }
```

to 

```
 protected function fields(): array
    {
        return [
            // fields...
        ];
    }
```

will save a lot of time :)

**Comment by tanthammar** [comment]
@rabol Please try [v2.2.0](https://github.com/tanthammar/tall-blueprint-addon/releases/tag/2.2.0).
Thank you for reporting, was a while ago I reviewed the code. Needed some overall love.
Please confirm that all is working as expected.
