### ISSUE TITLE
Cannot generate anything cause of this

### ISSUE THREAD

**Issue by ljoboy** [tanthammar/tall-blueprint-addon#7]
Every time I'm trying to generate anything I'm getting this :  
**Cannot assign Illuminate\Filesystem\Filesystem to property Tanthammar\TallBlueprintAddon\TallBlueprintGenerator::$files of type ?Illuminate\Contracts\Filesystem\Filesystem**
Laravel 9.52

**Comment by tanthammar** [comment]
I am sorry but I won't be able to investigate this error for a while. Would be happy if you could search a bit further on why you get the error.

**Comment by tanthammar** [comment]
Did your PR solve the problem?

**Comment by ljoboy** [comment]
Yes
